title: Cody Ilardo

theme: minima

minima:
  skin: solarized-dark

paginate: true
name: Cody Ilardo
permalink: /blog/:year/:month/:day/:title

author: 
  name: Cody Ilardo
  twitter: codyilardo
# show_excerpts: true

header_pages:
  - about.md
  - blog.html
