
theme: minima
remote_theme: "jekyll/minima"

title: Cody Ilardo

name: Cody S. Ilardo
email: codyilardo AT gmail DOT com
# author:

description: > # this means to ignore newlines until "show_excerpts:"
  I am a disciple, developer, and designer. 

minima:
  skin: solarized-dark

paginate: 5

permalink: /blog/:year/:month/:day/:title

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-pagination
  - jekyll-remote-theme