
theme: minima
# remote_theme: "jekyll/minima"

title: Cody Ilardo

name: Cody S. Ilardo
email: codyilardo AT gmail DOT com
# author:

# description: > # this means to ignore newlines until "show_excerpts:"
#    My name is Cody Ilardo, welcome to my website.  

minima:
  skin: dark

# paginate: 5

permalink: /blog/:year/:month/:day/:title

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
