title: Cody Ilardo

author:
  name: Cody Ilardo
  email: codyilardo AT gmail DOT com
description: > # this means to ignore newlines until "show_excerpts:"
  I am a disciple, developer, and designer. 

minima:
  skin: solarized-dark

paginate: true

name: Cody Ilardo
permalink: /blog/:year/:month/:day/:title

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag